<a href="https://colab.research.google.com/github/Chonthichasi/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data Structure (โครงสร้างข้อมูล)
เก็บข้อมูลหลายตัวไว้ด้วยกันอย่างเป็นระเบียบ

##List()
-เก็บอะไรก็ได้
-ลำดับการเก็บสำคัญ
```



In [1]:
list_a =[1,2,3,4,5,6] #square brackets วงแลบ[]

In [2]:
list_a

[1, 2, 3, 4, 5, 6]

In [3]:
list_b = ['ab',2,3.14,list_a]

In [4]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

###indexing การซื้อสมาชิกใน list ด้วยเลขลำดับของlist

In [5]:
list_a[3]

4

In [6]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [7]:
list_b[3][4]

5

In [8]:
list_a[6] #มันเกินสมาชิก้ลยerror

IndexError: ignored

In [54]:
list_a[-1]  # index-1 คือตัวสุดท้ายของlist

6

In [53]:
list_a[-4]

3

###การสร้างlist


In [ ]:
list_x1 = [] #แบบที่ 1 
list_x2 = list() #แบบที่2

In [ ]:
list_x1
list_x2 #ไม่ใช่คำสั่งprint

In [ ]:
print(list_x1)
print(list_x2)

### เพิ่มสมาชิกเข้าไปใน list ด้วย append()

In [ ]:
list_x1.append(2) 

In [ ]:
list_x1 #append 2 ข้างบน ข้อมูลมาอยู่ที่list_x1

In [ ]:
list_x1.append(4)
print(list_x1) 

In [ ]:
list_x1[0]

In [ ]:
list_x1[-1]

In [ ]:
list_x2

In [ ]:
list_x1.append('ha') #ข้อควรระวังควรรันแค่รอบเดียวเพราะสมาชิกจะเพิ่มตามจำนวนรัน

In [ ]:
list_x1

In [ ]:
list_x1.pop() #ตัดจำนวนสมาชิกที่ไม่ต้องการออกเริ่มจากหลังสุด

In [ ]:
list_x1

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

##len() ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))

In [ ]:
len(list_a)

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

In [ ]:
len(st_stat)

### List Slicing 
list[จุดเริ่มต้น:จุดสุดท้าย]

list[จุดเริ่มต้น:จุดสุดท้าย:step]

###colon

In [55]:
list_a

[1, 2, 3, 4, 5, 6]

In [56]:
list_a[2]

3

In [57]:
list_a[-3:]  #colon ดึงสมาชิก3ตัวสุดท้าย

[4, 5, 6]

In [58]:
list_a[1:4] #ไม่เอาเลข5เพราะข้างหลังมันโปร่ง

[2, 3, 4]

In [59]:
list_a[:]

[1, 2, 3, 4, 5, 6]

###Step

In [60]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [61]:
list_c[0:11:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [62]:
list_c[0:10:2]

[1, 3, 5, 7, 9]

In [63]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [64]:
list_c[::-2]

[13, 11, 9, 7, 5, 3, 1]

###range()

In [65]:
range(21)

range(0, 21)

In [66]:
a = list(range(21))

In [67]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [68]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

###HW คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้ใช้คำสั่ง split() ช่วย (print  ออกมาให้สวยงาม)
- 12:30:15

- 13:41:07

- 09:11:50

- 21:30:15

- 03:10:15

In [9]:
# 12:30:15
H1 = "12:30:15"
list_H1 = H1.split (":")
Hour = int(list_H1[0])*60*60
Minute = int(list_H1[1])*60
Second= int(list_H1[2])
Total_H1 = Hour+Minute+Second
print (f' {H1} แปลงเป็นวินาทีได้ {Total_H1} วินาที')

 12:30:15 แปลงเป็นวินาทีได้ 45015 วินาที


In [10]:
# 13:41:07
H2 = "13:41:07"
list_H2 = H2.split (":")
Hour = int(list_H2[0])*60*60
Minute = int(list_H2[1])*60
Second= int(list_H2[2])
Total_H2 = Hour+Minute+Second
print (f' {H2} แปลงเป็นวินาทีได้ {Total_H2} วินาที')

 13:41:07 แปลงเป็นวินาทีได้ 49267 วินาที


In [11]:
# 09:11:50
H3 = "09:11:50"
list_H3 = H3.split (":")
Hour = int(list_H3[0])*60*60
Minute = int(list_H3[1])*60
Second= int(list_H3[2])
Total_H3 = Hour+Minute+Second
print (f' {H3} แปลงเป็นวินาทีได้ {Total_H3} วินาที')

 09:11:50 แปลงเป็นวินาทีได้ 33110 วินาที


In [12]:
# 21:30:15
H4 = "21:30:15"
list_H4 = H4.split (":")
Hour = int(list_H4[0])*60*60
Minute = int(list_H4[1])*60
Second= int(list_H4[2])
Total_H4 = Hour+Minute+Second
print (f' {H4} แปลงเป็นวินาทีได้ {Total_H4} วินาที')

 21:30:15 แปลงเป็นวินาทีได้ 77415 วินาที


In [13]:
# 03:10:15
H5 = "03:10:15"
list_H5 = H5.split (":")
Hour = int(list_H5[0])*60*60
Minute = int(list_H5[1])*60
Second= int(list_H5[2])
Total_H5 = Hour+Minute+Second
print (f' {H5} แปลงเป็นวินาทีได้ {Total_H5} วินาที')

 03:10:15 แปลงเป็นวินาทีได้ 11415 วินาที


##Dictionary
- คล้าย list()
- index เป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลข
- ลำดับไม่มีความสำคัญ



In [15]:
dict_a = {1:'happy','N':'New','2022':'year'} #curly brakets{}

###การชี้สมาชิกใน Dictionary

```
# This is formatted as code
```



In [16]:
dict_a[1]

'happy'

In [18]:
dict_a['N']

'New'

In [19]:
dict_a.keys() #การเรียกดูสมชิกในdict

dict_keys([1, 'N', '2022'])

In [20]:
dict_a.values() #การเรียกดูค่าในdict

dict_values(['happy', 'New', 'year'])

### การเพิ่มสมาชิกเข้าไปใน Dictionary

In [21]:
dict_a[7] = 3.14

In [22]:
dict_a

{1: 'happy', '2022': 'year', 7: 3.14, 'N': 'New'}

In [23]:
dict_a['N'] = 'NNNNEEEEWWWW' #ถ้าindexซ้ำมันจะอัพค่าใหม่เข้าไปเลย

In [24]:
dict_a

{1: 'happy', '2022': 'year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

##Numpy Array

### 1D array

In [25]:
import numpy

In [38]:
list_A = [1,2,3,4,5]

In [27]:
arr_a = numpy.array([1,2,3,4,5])

In [28]:
arr_a

array([1, 2, 3, 4, 5])

In [30]:
list_a

[1, 2, 3, 4, 5, 6]

In [29]:
arr_a[0]

1

In [31]:
list_a[0]

1

In [86]:
list_A

[1, 2, 3, 4, 'Christmas']

In [32]:
5*arr_a # Matrix (Scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [40]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
arr_b = numpy.array([10,20,30,40,50])

In [42]:
print(arr_a)

[1 2 3 4 5]


In [43]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [44]:
arr_a * arr_b

array([ 10,  40,  90, 160, 250])

### 2D array

In [46]:
import numpy as np

In [50]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [51]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
print(arr2_z)

[[1 2 3]
 [4 5 6]]


In [70]:
arr2_z.shape  #ดูขนาดสมาชิกในarray

(2, 3)

In [71]:
arr_a.shape

(5,)

### np.zeros()

In [73]:
arr2_3_5_0 = np.zeros((3,5)) #อยากให้มีขนาด3*5

In [78]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
arr2_3_5_0[1,2] = 9 #อยากให้ค่าแถวที่1หลักที่2มีค่าเท่ากับ9

In [81]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
arr2_3_5_0[1,2] 

9.0

In [89]:
print(list_A)

[1, 2, 3, 4, 'Christmas']


In [88]:
print(list_A)  #เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 'Christmas']
[1, 2, 3, 4, 'Christmas']


###np.ones()

In [90]:
arr2_4_5_1 = np.ones((4,5))

In [91]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
arr2_4_5_200 = 200*np.ones((4,5))

In [94]:
arr2_4_5_200 

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matriz Operations

การบวก ลบ Matrix บวก ลบ ตำแหน่งเดียวกัน

In [96]:
arr2_4_5_200 + arr2_4_5_0 # การบวกลบ matix ต้องมีshapเท่ากัน

NameError: ignored

In [97]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

### การคูณ Matrix
- $aM$ สเกลล่า*matrix คูณกระจาเข้าไปเลย
- $M*N$ M*M (แถวคูณหลัก)

In [98]:
5*arr_a # 

array([ 5, 10, 15, 20, 25])

In [102]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[2,3,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [103]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [104]:
mat_b

array([[ 2,  3,  5],
       [ 2,  4, -7]])

In [105]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

a*c b*c

In [106]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [107]:
np.dot(mat_b,mat_c)

array([[ 51,  69],
       [-29, -33]])

In [108]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [112]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[ 10  18 -11]
 [ 20  36 -22]
 [ 32  57 -28]]


In [110]:
mat_a * mat_b #คูณตำแหน่งเดียวกัน

array([[  4,   9,  25],
       [  8,  24, -49]])

### Matric Sclicing

In [113]:
mat_X[:2,:2]

array([[10, 18],
       [20, 36]])

HW3
1. สร้าง array ที่เป็นต้น chritsmas
2. slic เลข1 ออกมาจาก array HW3 ด้วยการ Sclic แค่ครั้งเดียว

In [116]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Panda Dataframe (แยกออกไปเป็น Notebook เฉพาะ)